version: "3.7"

services:
  ryuk_s_challenge:
    image: ryuk_s_challenge:0.1.0
    build:
      context: . # relative to docker-compose.yml
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    restart: unless-stopped
